FROM apache/spark:4.2.0
USER root
FROM python:3.14-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN pip install jupyterlab pyspark==4.2.0 && mkdir -p /home/spark && chown spark:spark /home/spark
ENV HOME=/home/spark
USER spark


